apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prometheuses.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 1
                  description: "Number of replicas for Prometheus deployment"
  names:
    kind: Prometheus
    plural: prometheuses
    singular: prometheus
    shortNames:
      - prom
  scope: Namespaced

